// <copyright file="DatabaseLog.cs" company="Farooq Mahmud">
// Copyright (c) Farooq Mahmud. All rights reserved.
// </copyright>

namespace DataAccess.EFCore.Entities
{
    using System;

    /// <summary>
    /// Audit table tracking all DDL changes made to the AdventureWorks database. Data is captured by the database trigger ddlDatabaseTriggerLog.
    /// </summary>
    public class DatabaseLog
    {
        /// <summary>
        /// Gets or sets primary key for DatabaseLog records.
        /// </summary>
        public int DatabaseLogId { get; set; }

        /// <summary>
        /// Gets or sets the date and time the DDL change occurred.
        /// </summary>
        public DateTime PostTime { get; set; }

        /// <summary>
        /// Gets or sets the user who implemented the DDL change.
        /// </summary>
        public string DatabaseUser { get; set; } = null!;

        /// <summary>
        /// Gets or sets the type of DDL statement that was executed.
        /// </summary>
        public string Event { get; set; } = null!;

        /// <summary>
        /// Gets or sets the schema to which the changed object belongs.
        /// </summary>
        public string? Schema { get; set; }

        /// <summary>
        /// Gets or sets the object that was changed by the DDL statment.
        /// </summary>
        public string? Object { get; set; }

        /// <summary>
        /// Gets or sets the exact Transact-SQL statement that was executed.
        /// </summary>
        public string Tsql { get; set; } = null!;

        /// <summary>
        /// Gets or sets the raw XML data generated by database trigger.
        /// </summary>
        public string XmlEvent { get; set; } = null!;
    }
}
