#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["DataLoader/DataLoader.csproj", "DataLoader/"]
COPY ["DataAccess.EFCore/DataAccess.EFCore.csproj", "DataAccess.EFCore/"]
RUN dotnet restore "DataLoader/DataLoader.csproj"
COPY . .
WORKDIR "/src/DataLoader"
RUN dotnet build "DataLoader.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DataLoader.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY Data/data.csv /app/Data/data.csv
ENTRYPOINT ["dotnet", "DataLoader.dll"]